<a href="https://colab.research.google.com/github/ArunkumarRK/tensor_network/blob/main/fundamentals_of_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

What is tensor?
Tensor is nothinf but a kind of datatype/ data structure similar to


*   List
*   int
*   str
*   dict
*   set
*   tensor

In [ ]:
import numpy as np
import tensorflow as tf


In [ ]:
height =162
weight=66.5
height, weight


(162, 66.5)

In [ ]:
type(height), type(weight)

(int, float)

In [ ]:
vector=[1,2,3,4,5]
vector, type(vector), len(vector)

([1, 2, 3, 4, 5], list, 5)

In [ ]:
matrix=[[1,2,3],
        [3,4,5]]
matrix, type(matrix), len(matrix)

([[1, 2, 3], [3, 4, 5]], list, 2)

In [ ]:
matrix_1=np.array(matrix)
matrix_1, type(matrix_1), matrix_1.shape

(array([[1, 2, 3],
        [3, 4, 5]]),
 numpy.ndarray,
 (2, 3))

**Creating tensors**

In [ ]:
scalar=tf.constant(3)
scalar, type(scalar)

(<tf.Tensor: shape=(), dtype=int32, numpy=3>,
 tensorflow.python.framework.ops.EagerTensor)

In [ ]:
scalar.ndim

0

In [ ]:
vector=tf.constant(np.arange(10))
vector, vector.shape, vector.ndim

(<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>,
 TensorShape([10]),
 1)

In [ ]:
tensor_n=tf.constant(range(100), shape=(5,2,2,5))

tensor_n, tensor_n.shape, tensor_n.ndim

(<tf.Tensor: shape=(5, 2, 2, 5), dtype=int32, numpy=
 array([[[[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9]],
 
         [[10, 11, 12, 13, 14],
          [15, 16, 17, 18, 19]]],
 
 
        [[[20, 21, 22, 23, 24],
          [25, 26, 27, 28, 29]],
 
         [[30, 31, 32, 33, 34],
          [35, 36, 37, 38, 39]]],
 
 
        [[[40, 41, 42, 43, 44],
          [45, 46, 47, 48, 49]],
 
         [[50, 51, 52, 53, 54],
          [55, 56, 57, 58, 59]]],
 
 
        [[[60, 61, 62, 63, 64],
          [65, 66, 67, 68, 69]],
 
         [[70, 71, 72, 73, 74],
          [75, 76, 77, 78, 79]]],
 
 
        [[[80, 81, 82, 83, 84],
          [85, 86, 87, 88, 89]],
 
         [[90, 91, 92, 93, 94],
          [95, 96, 97, 98, 99]]]], dtype=int32)>,
 TensorShape([5, 2, 2, 5]),
 4)

In [ ]:
tensor_variable=tf.Variable([1,2,3,4],dtype=tf.float16)
tensor_variable

<tf.Variable 'Variable:0' shape=(4,) dtype=float16, numpy=array([1., 2., 3., 4.], dtype=float16)>

In [ ]:
tensor_variable.dtype

tf.float16

In [ ]:
tensor_variable.dtype.ndim

AttributeError: 'DType' object has no attribute 'ndim'

In [ ]:
tensor_variable[0].assign(5)
tensor_variable[1].assign(10)


<tf.Variable 'UnreadVariable' shape=(4,) dtype=float16, numpy=array([ 5., 10.,  3.,  4.], dtype=float16)>

**Uniform distribution**

In [ ]:
tensor_random=tf.random.uniform(shape=(2,2))
tensor_random

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.35305202, 0.5875462 ],
       [0.15042937, 0.14208555]], dtype=float32)>

**Normal Distribution**

In [ ]:
tensor_random_normal=tf.random.normal(shape=(2,3))
tensor_random_normal

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1.4682448 , -0.5780113 , -0.10381896],
       [ 0.87525   ,  0.68607247,  1.843282  ]], dtype=float32)>

In [ ]:
#every run should return same random value based on specific number
tf.random.set_seed(42)
tensor_random_ss=tf.random.uniform(shape=(2,3))
tensor_random_ss  #it'll return same values again and again

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 ],
       [0.46448255, 0.03366041, 0.68467236]], dtype=float32)>

In [ ]:
#0's and 1's tensor creation
tensor_ones=tf.ones(shape=(2,2))
tensor_zeros=tf.zeros(shape=(2,3))
tensor_ones, tensor_zeros


(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[0., 0., 0.],
        [0., 0., 0.]], dtype=float32)>)

**Tensor Attribute**

In [ ]:
tensor_ones.shape, tensor_ones.ndim, tf.size(tensor_ones), tensor_ones.dtype

(TensorShape([2, 2]),
 2,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>,
 tf.float32)

In [ ]:
tf.size(tensor_ones).numpy()

np.int32(4)